[package]
name = "hezen_runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["color"]
color = ["dep:colored"]

[dependencies]
regex = "1.7"
once_cell = "1.16"
colored = { version = "1.0", optional = true }
